### ISSUE TITLE
Errror in pytest

### ISSUE THREAD

**Issue by jbdav** [ATOMconsortium/AMPL#12]
Hello,

I'm trying to run the Delaney Python script:

conda activate atomsci
cd atomsci/ddm/test/integrative/delaney_RF
pytest

I keep running into this error:

File "/home/.local/lib/python3.6/site-packages/atomsci/ddm/pipeline/model_pipeline.py", line 28, in <module>
    from atomsci.ddm.pipeline import model_tracker as trkr
  File "/home/.local/lib/python3.6/site-packages/atomsci/ddm/pipeline/model_tracker.py", line 14, in <module>
    from atomsci.clients import MLMTClient
**ModuleNotFoundError: No module named 'atomsci.clients'**

is this module available?

thanks!

**Comment by mcloughlin2** [comment]
This should be fixed now. The code was trying to import a package that's only used locally at ATOM, without failing gracefully. Pull the latest code from the master branch and try again.
